### ISSUE TITLE
selectedLineBgColor not working

### ISSUE THREAD

**Issue by cj** [jesseduffield/lazynpm#5]
**Describe the bug**
Setting the gui theme options for selectedLineBgColor has no effect.

**To Reproduce**
This is the same config I have for lazygit:
```yml
reporting: "off"
startuppopupversion: 1
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
```

**Expected behavior**
It should have a white background like lazygit:
![CleanShot 2020-08-14 at 17 23 06](https://user-images.githubusercontent.com/1819/90297033-dfb3ab80-de52-11ea-8436-fa8013a83fc9.png)
Except it looks like:
![CleanShot 2020-08-14 at 17 24 26](https://user-images.githubusercontent.com/1819/90297097-0c67c300-de53-11ea-85ab-bb2bafba34a1.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
Mac
lazynpm 0.1.4
